apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: anJrb2w1cHc=
  CLOUDINARY_KEY: MjY2OTg4OTUyOTc4Nzk0
  CLOUDINARY_SECRET: UUIwR21uSURhY3E1aTRIckw4WkFlczNzWjRv
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljR0ZzYkdGdGRYSmhiR2xrYUdGeUxUQXhJaXdpWVNJNkltTnRjbXR0TVdRMlpqQm1iR296TUhGMlluWjVkRE5pTTJ3aWZRLkt3VGpqTXR6dUFPb25wSXFZU3Z3U0E=
  DB_URL: bW9uZ29kYitzcnY6Ly9wYWxsYW11cmFsaWRoYXIwMV9kYl91c2VyOlJSWDBlV1pQSHRrc05vUW9AY2x1c3RlcjAuN2hlYTcwdS5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
